/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { AssetInfo } from "@/contracts/generated/positions/Positions.types";

export type Decimal = string;
export type Addr = string;
export interface Config {
  cdt_denom: string;
  desired_asset: string;
  discount_increase: Decimal;
  discount_increase_timeframe: number;
  governance_contract: Addr;
  initial_discount: Decimal;
  mbrn_denom: string;
  oracle_contract: Addr;
  osmosis_proxy: Addr;
  owner: Addr;
  positions_contract: Addr;
  send_to_stakers: boolean;
  staking_contract: Addr;
  twap_timeframe: number;
}
export type Uint128 = string;
export interface DebtAuction {
  auction_start_time: number;
  remaining_recapitalization: Uint128;
  repayment_positions: RepayPosition[];
  send_to: AuctionRecipient[];
}
export interface RepayPosition {
  position_info: UserInfo;
  repayment: Uint128;
}
export interface UserInfo {
  position_id: Uint128;
  position_owner: string;
}
export interface AuctionRecipient {
  amount: Uint128;
  recipient: Addr;
}
export type ExecuteMsg = {
  start_auction: {
    auction_asset: Asset;
    repayment_position_info?: UserInfo | null;
    send_to?: string | null;
  };
} | {
  swap_for_m_b_r_n: {};
} | {
  swap_for_fee: {
    auction_asset: AssetInfo;
  };
} | {
  remove_auction: {};
} | {
  update_config: UpdateConfig;
};
export interface Asset {
  amount: Uint128;
  info: AssetInfo;
}
export interface UpdateConfig {
  cdt_denom?: string | null;
  desired_asset?: string | null;
  discount_increase?: Decimal | null;
  discount_increase_timeframe?: number | null;
  governance_contract?: string | null;
  initial_discount?: Decimal | null;
  mbrn_denom?: string | null;
  oracle_contract?: string | null;
  osmosis_proxy?: string | null;
  owner?: string | null;
  positions_contract?: string | null;
  send_to_stakers?: boolean | null;
  staking_contract?: string | null;
  twap_timeframe?: number | null;
}
export interface FeeAuction {
  auction_asset: Asset;
  auction_start_time: number;
}
export interface InstantiateMsg {
  discount_increase: Decimal;
  discount_increase_timeframe: number;
  governance_contract: string;
  initial_discount: Decimal;
  mbrn_denom: string;
  oracle_contract: string;
  osmosis_proxy: string;
  owner?: string | null;
  positions_contract: string;
  staking_contract: string;
  twap_timeframe: number;
}
export type QueryMsg = {
  config: {};
} | {
  debt_auction: {};
} | {
  ongoing_fee_auctions: {
    auction_asset?: AssetInfo | null;
    limit?: number | null;
    start_after?: number | null;
  };
};