// AUTO-GENERATED by scripts/sync-abis.ts from membrane-solidity out/Acquisition.sol — do not edit.
export const acquisitionAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "governance_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "cfg",
        "type": "tuple",
        "internalType": "struct Acquisition.ProtocolConfig",
        "components": [
          {
            "name": "transmuter_contract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "neutron_proxy",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "cdp_contract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "deposit_period_days",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "withdrawal_period_days",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deposit_token",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "minimum_deposit",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mbrn_denom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "staking_contract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ltv_disco_contract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "discounts_contract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "cliff_period_seconds",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "acqCfg",
        "type": "tuple",
        "internalType": "struct Acquisition.AcquisitionConfigParams",
        "components": [
          {
            "name": "base_acquisition_rate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initial_acquisition_amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "max_mbrn_emission",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "target_utilization",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bump_increment",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bump_interval_seconds",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "reduction_speed_multiplier",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "efficiency_threshold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "max_rate_change_per_mutation",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "max_bump_rate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mutation_cooldown_seconds",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "accrual_ramp_seconds",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "accrual_ramp_start_fraction",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "acqSt",
        "type": "tuple",
        "internalType": "struct Acquisition.AcquisitionModelState",
        "components": [
          {
            "name": "current_acquisition_rate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "accrued_pool",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "last_accrual_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "pool_maxed",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "bump_rate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "last_bump_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "window_timers_started",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "first_deposit_time_set",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "first_deposit_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deposit_event_count",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "total_new_deposits",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "last_mutation_efficiency_set",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "last_mutation_efficiency",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "last_mutation_time_set",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "last_mutation_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "efficiency_clamped",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "mbrn_",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "acceptOwnerTransfer",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "accruePool",
    "inputs": [
      {
        "name": "newAccrued",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "newRate",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "newBumpRate",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "poolMaxed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "acquisitionConfig",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Acquisition.AcquisitionConfigParams",
        "components": [
          {
            "name": "base_acquisition_rate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initial_acquisition_amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "max_mbrn_emission",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "target_utilization",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bump_increment",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bump_interval_seconds",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "reduction_speed_multiplier",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "efficiency_threshold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "max_rate_change_per_mutation",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "max_bump_rate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mutation_cooldown_seconds",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "accrual_ramp_seconds",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "accrual_ramp_start_fraction",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acquisitionHistoryLen",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acquisitionState",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Acquisition.AcquisitionModelState",
        "components": [
          {
            "name": "current_acquisition_rate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "accrued_pool",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "last_accrual_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "pool_maxed",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "bump_rate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "last_bump_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "window_timers_started",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "first_deposit_time_set",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "first_deposit_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deposit_event_count",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "total_new_deposits",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "last_mutation_efficiency_set",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "last_mutation_efficiency",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "last_mutation_time_set",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "last_mutation_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "efficiency_clamped",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cancelConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cancelOwnerTransfer",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "claim",
    "inputs": [
      {
        "name": "windowId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "userOverride",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "currentAcquisitionWindow",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Acquisition.AcquisitionWindow",
        "components": [
          {
            "name": "window_id",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "start_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deposit_end",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "withdrawal_end",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deposit_period_days",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "total_deposit_amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "acquisition_budget",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "currentWindowId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "depositExists",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "windowId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "executeConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getDeposit",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "windowId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Acquisition.AcquisitionDeposit",
        "components": [
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deposit_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "vested_at",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "sent_to_disco",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "mbrn_claim_amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mbrn_claim_amount_set",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "disco_deposit_id",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "disco_deposit_id_set",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "claimed_mbrn_amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "claimed_mbrn_amount_set",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "disco_asset",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "disco_asset_set",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "disco_slot",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "disco_slot_set",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getIntents",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "internalType": "struct Acquisition.MbrnIntentOption[]",
        "components": [
          {
            "name": "kind",
            "type": "uint8",
            "internalType": "enum Acquisition.MbrnIntentKind"
          },
          {
            "name": "asset",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "slot",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ratio",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lockDurationSet",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "lockDurationDays",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "governance",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "ltvDisco",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "transmuter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "intentsRatioSum",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "sum",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isInitialized",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "liveAccessSnapshot",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct AcquisitionInvariants.Config",
        "components": [
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "governance",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "cliff_period_seconds",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "liveConfigSnapshot",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct AcquisitionInvariants.AcquisitionConfig",
        "components": [
          {
            "name": "max_mbrn_emission",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "max_bump_rate",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "liveStateSnapshot",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct AcquisitionInvariants.AcquisitionState",
        "components": [
          {
            "name": "accrued_pool",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "bump_rate",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "window_timers_started",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "first_deposit_time_set",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "liveWindowSnapshot",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct AcquisitionInvariants.AcquisitionWindow",
        "components": [
          {
            "name": "window_id",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "total_deposit_amount",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "mbrn",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingChanges",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "proposer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "createdAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proposeOwnerTransfer",
    "inputs": [
      {
        "name": "proposed",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "protocolConfig",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Acquisition.ProtocolConfig",
        "components": [
          {
            "name": "transmuter_contract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "neutron_proxy",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "cdp_contract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "deposit_period_days",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "withdrawal_period_days",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deposit_token",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "minimum_deposit",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mbrn_denom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "staking_contract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ltv_disco_contract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "discounts_contract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "cliff_period_seconds",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requestConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "sendAcquisitionRewardsToDisco",
    "inputs": [
      {
        "name": "windowId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "slot",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "startAcquisitionWindow",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitDeposit",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "intents",
        "type": "tuple[]",
        "internalType": "struct Acquisition.MbrnIntentOption[]",
        "components": [
          {
            "name": "kind",
            "type": "uint8",
            "internalType": "enum Acquisition.MbrnIntentKind"
          },
          {
            "name": "asset",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "slot",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ratio",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lockDurationSet",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "lockDurationDays",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "manager",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "affiliate",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "updateGovernance",
    "inputs": [
      {
        "name": "newGovernance",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "userIntentsSet",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AcquisitionWindowStarted",
    "inputs": [
      {
        "name": "windowId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "startTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigChangeCancelled",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigChangeExecuted",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigChangeRequested",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      },
      {
        "name": "proposer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DepositSubmitted",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "windowId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "firstInWindow",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "manager",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "affiliate",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DepositWithdrawn",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "windowId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "clawbackTriggered",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GovernanceUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "by",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LtvDiscoUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MbrnClaimed",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "windowId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnerTransferAccepted",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnerTransferProposed",
    "inputs": [
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "proposed",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipRenounced",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PoolAccrued",
    "inputs": [
      {
        "name": "newAccrued",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "newRate",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "newBumpRate",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "poolMaxed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "bumpChanged",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RewardsSentToDisco",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "windowId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "asset",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "slot",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "boostedAmount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TransmuterUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadySentToDisco",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "windowId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "BumpAboveMaxBump",
    "inputs": [
      {
        "name": "bump",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cap",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ChangeAlreadyPending",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "CliffNotReached",
    "inputs": [
      {
        "name": "nowTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "vestedAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "DepositPeriodEnded",
    "inputs": [
      {
        "name": "nowTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "depositEnd",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "DepositTooSmall",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minimum",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "IntentRatiosNotOne",
    "inputs": [
      {
        "name": "sum",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "MintAmountZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoDepositForKey",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "windowId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoDiscoConfigured",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoPendingChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotGovernance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwnerOrGovernance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPendingOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnerGovernanceCollision",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PoolUnderMaxFailed",
    "inputs": [
      {
        "name": "accruedPool",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxEmission",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RateAboveMaxBump",
    "inputs": [
      {
        "name": "rate",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cap",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "RateAssuranceFailed",
    "inputs": [
      {
        "name": "transmuterTotal",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "windowTotal",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TimelockExpired",
    "inputs": [
      {
        "name": "nowTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "TimelockNotElapsed",
    "inputs": [
      {
        "name": "nowTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownConfigField",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "WithdrawAmountExceedsDeposit",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "owned",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "WithdrawalWindowStillOpen",
    "inputs": [
      {
        "name": "nowTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "withdrawalEnd",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  }
] as const
