// AUTO-GENERATED by scripts/sync-abis.ts from membrane-solidity out/Auction.sol — do not edit.
export const auctionAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "governance_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "cdt_",
        "type": "address",
        "internalType": "contract IERC20"
      },
      {
        "name": "cfg",
        "type": "tuple",
        "internalType": "struct Auction.Config",
        "components": [
          {
            "name": "mbrnDenom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "cdtDenom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "desiredAsset",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "positionsContract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "stakingContract",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "twapTimeframeM",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "initialDiscount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "discountIncreaseTimeframeS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "discountIncrease",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sendToStakers",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "delayWindowM",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "DISCOUNT_CAP",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_BUY_RECURSION_DEPTH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_DISCOUNT_INCREASE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_DISCOUNT_PCT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_TIMEFRAME_S",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_TWAP_TIMEFRAME_M",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_DISCOUNT_INCREASE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_DISCOUNT_PCT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_TIMEFRAME_S",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_TWAP_TIMEFRAME_M",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnerTransfer",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "blacklistAuctionDuration",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "blacklistAuctionPrice",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "blacklistAuctions",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "sourcePositionId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "custodyClone",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "frozenUsdcAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sendExcessTo",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "auctionStartTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "auctionEndTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "exists",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "buySuppliedMBRN",
    "inputs": [
      {
        "name": "depth",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "buyerOverride",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "sentCdt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "mbrnPaid",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cdtUsed",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cancelBlacklistAuction",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cancelConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cancelOwnerTransfer",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cdpBlacklistExtraction",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICdpBlacklistExtraction"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cdpShortfallHandler",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICdpShortfallHandler"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cdt",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "concludeUnsoldBlacklistAuction",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "config",
    "inputs": [],
    "outputs": [
      {
        "name": "mbrnDenom",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "cdtDenom",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "desiredAsset",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "positionsContract",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "stakingContract",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "twapTimeframeM",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "initialDiscount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "discountIncreaseTimeframeS",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "discountIncrease",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sendToStakers",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "delayWindowM",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "debtBurnSite",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IDebtBurnSite"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "executeConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "feeAssetToken",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeAuctions",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "auctionAssetDenom",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "auctionAssetAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "auctionStartTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "exists",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "fulfillBadDebt",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sentCdt",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "applied",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "refund",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getAllocation",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Auction.AssetBadDebtAllocation",
        "components": [
          {
            "name": "asset",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "mbrnAllocated",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mbrnUsed",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "cdtBadDebt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "cdtFulfilled",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getDiscountRatio",
    "inputs": [
      {
        "name": "auctionStart",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "governance",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "heldProceeds",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "cdpShortfallHandler_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "debtBurnSite_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "ltvDiscoContract_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "ltvDiscoSink_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "revenueRouter_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isAllocationActive",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isInitialized",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ltvDiscoContract",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ltvDiscoSink",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ILtvDiscoMbrnSink"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "mbrnSale",
    "inputs": [],
    "outputs": [
      {
        "name": "maxCdt",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cdtFulfilled",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "auctionStartTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "supplier",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "mbrnSaleActive",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingChanges",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "proposer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "createdAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proposeOwnerTransfer",
    "inputs": [
      {
        "name": "proposed",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "removeAuction",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requestConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revenueRouter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IRevDistRevenueRouter"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "saleAssetAt",
    "inputs": [
      {
        "name": "i",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "saleAssetCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "saleAssetsLength",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setBlacklistAuctionDuration",
    "inputs": [
      {
        "name": "duration",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setCdpBlacklistExtraction",
    "inputs": [
      {
        "name": "target",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setFeeAssetToken",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "contract IERC20"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settleBlacklistAuction",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "startAuction",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "startBlacklistAuction",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "startMBRNSale",
    "inputs": [
      {
        "name": "maxCdt",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "mbrnAllocation",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "swapForFee",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "paid",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "payout",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "sweepCdtTo",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "updateGovernance",
    "inputs": [
      {
        "name": "newGovernance",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AuctionRemoved",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AuctionStarted",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newAmount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "totalAmount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "startTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BadDebtBurned",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BadDebtFulfilled",
    "inputs": [
      {
        "name": "payer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "applied",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "refund",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "assetClosed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BlacklistAuctionCancelled",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BlacklistAuctionConcludedUnsold",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BlacklistAuctionDurationUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "current",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BlacklistAuctionSettled",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "winner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "price",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BlacklistAuctionStarted",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "clone",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "usdcAmount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "sendExcessTo",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "endTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CdpBlacklistExtractionUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CdpShortfallHandlerUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CdtSwept",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigChangeCancelled",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigChangeExecuted",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigChangeRequested",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      },
      {
        "name": "proposer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DebtBurnSiteUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeAssetTokenUpdated",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeeSwap",
    "inputs": [
      {
        "name": "buyer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "denom",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "paid",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "payout",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "remaining",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GovernanceUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "by",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LtvDiscoContractUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LtvDiscoSinkUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MBRNBought",
    "inputs": [
      {
        "name": "buyer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "mbrnPaid",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "cdtBurned",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "depth",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MBRNSaleCleared",
    "inputs": [],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MBRNSaleStarted",
    "inputs": [
      {
        "name": "supplier",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "asset",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "maxCdt",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "mbrnAllocation",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MBRNSaleTerminated",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "reservedCdt",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "cdtFulfilled",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "shortfall",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnerTransferAccepted",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnerTransferProposed",
    "inputs": [
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "proposed",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipRenounced",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProceedsForwardedToRevDist",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "router",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProceedsHeldForSweep",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RevenueRouterUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AuctionNotFound",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "BlacklistAuctionActive",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "BlacklistAuctionDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BlacklistAuctionDurationOutOfRange",
    "inputs": [
      {
        "name": "value",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "BlacklistAuctionExpired",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "BlacklistAuctionNotFound",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "BlacklistAuctionStillLive",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "CdtAuctionForbidden",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ChangeAlreadyPending",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "CloneStillFrozen",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "DiscountOutOfRange",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "min",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "max",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "FeeAssetUnmapped",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidConfig",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvariantViolation_inv_discount_increase_bounded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvariantViolation_inv_discount_initial_bounded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvariantViolation_inv_mbrn_sale_summed_consistent",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvariantViolation_inv_no_cdt_in_fee_auctions",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvariantViolation_inv_no_unilateral_capital_loss_path_AU",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvariantViolation_inv_owner_governance_distinct",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvariantViolation_inv_timeframe_bounded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvariantViolation_inv_twap_bounded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MBRNSaleAlreadyActive",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MbrnUsedAboveAllocation",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "attempted",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cap",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoActiveAllocation",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoActiveAllocations",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoActiveMBRNSale",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoPendingChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotAuthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotGovernance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwnerOrGovernance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPendingOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NothingToAuction",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnerGovernanceCollision",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RecursionDepthExceeded",
    "inputs": [
      {
        "name": "depth",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RouterAlreadyWired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SelfCallRequired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TimeframeOutOfRange",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "min",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "max",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TimelockExpired",
    "inputs": [
      {
        "name": "nowTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "TimelockNotElapsed",
    "inputs": [
      {
        "name": "nowTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "TwapOutOfRange",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "min",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "max",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownConfigField",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "UsdcNotBlacklisted",
    "inputs": [
      {
        "name": "positionId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  }
] as const
