// AUTO-GENERATED by scripts/sync-abis.ts from membrane-solidity out/Collateral.sol — do not edit.
export const collateralAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "governance_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "genesisAssets",
        "type": "tuple[]",
        "internalType": "struct Collateral.AssetParams[]",
        "components": [
          {
            "name": "denom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "temp_ltv",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "max_threshold_to_delay",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "oracle_source",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "enabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "onboarding_window_end",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ONBOARDING_WINDOW_DURATION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnerTransfer",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "addAssetAtInstantiate",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct Collateral.AssetParams",
        "components": [
          {
            "name": "denom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "temp_ltv",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "max_threshold_to_delay",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "oracle_source",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "enabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "onboarding_window_end",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assetAt",
    "inputs": [
      {
        "name": "i",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assetCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assetExists",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assetList",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assets",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "temp_ltv",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "max_threshold_to_delay",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "oracle_source",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "onboarding_window_end",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cancelConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cancelOwnerTransfer",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "currentMaxLTV",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "ltv",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "discoOracle",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IDiscoOracle"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "executeConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "governance",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "discoOracle_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "ltvDiscoContract_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isAssetInOnboarding",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isInitialized",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isValidCollateral",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ltvDiscoContract",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maybeOnboard",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "route",
        "type": "tuple",
        "internalType": "struct V3PoolSelector.Route",
        "components": [
          {
            "name": "pools",
            "type": "address[]",
            "internalType": "address[]"
          },
          {
            "name": "fees",
            "type": "uint24[]",
            "internalType": "uint24[]"
          },
          {
            "name": "zeroForOne",
            "type": "bool[]",
            "internalType": "bool[]"
          },
          {
            "name": "length",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      },
      {
        "name": "startingLtv",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "windowEnd",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "peersForOnboarding",
    "inputs": [
      {
        "name": "newAsset",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "peers",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingChanges",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "proposer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "createdAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proposeOwnerTransfer",
    "inputs": [
      {
        "name": "proposed",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requestConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requireBorrowAllowed",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "totalBorrowedSoFar",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "requestedAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "lentIntoTranche",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "requireWithdrawAllowed",
    "inputs": [
      {
        "name": "asset",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "updateAsset",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct Collateral.AssetParams",
        "components": [
          {
            "name": "denom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "temp_ltv",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "max_threshold_to_delay",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "oracle_source",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "enabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "onboarding_window_end",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "updateGovernance",
    "inputs": [
      {
        "name": "newGovernance",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AssetAddedAtInstantiate",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "tempLtv",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AssetMaybeOnboarded",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "startingLtv",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "windowEnd",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AssetUpdated",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigChangeCancelled",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigChangeExecuted",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigChangeRequested",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      },
      {
        "name": "proposer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DiscoOracleUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GovernanceUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "by",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LtvDiscoContractUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnerTransferAccepted",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnerTransferProposed",
    "inputs": [
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "proposed",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipRenounced",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AssetAlreadyRegistered",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "AssetInOnboardingWindow",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "windowEnd",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "AssetNotRegistered",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "BorrowExceedsTrancheCap",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "totalAfter",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "lent",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ChangeAlreadyPending",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LtvAboveHardCap",
    "inputs": [
      {
        "name": "attempted",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cap",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoPendingChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotGovernance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotLtvDisco",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwnerOrGovernance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPendingOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnerGovernanceCollision",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StartingLtvAboveCap",
    "inputs": [
      {
        "name": "attempted",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cap",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TempLtvImmutable",
    "inputs": [
      {
        "name": "attempted",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "existing",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TimelockExpired",
    "inputs": [
      {
        "name": "nowTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "TimelockNotElapsed",
    "inputs": [
      {
        "name": "nowTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownConfigField",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "WindowEndImmutable",
    "inputs": [
      {
        "name": "attempted",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "existing",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "WindowEndMismatch",
    "inputs": [
      {
        "name": "attempted",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expected",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const
