// AUTO-GENERATED by scripts/sync-abis.ts from membrane-solidity out/FrontendLens.sol — do not edit.
export const frontendLensAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "collateral_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "cdp_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "auction_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "auction",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAuctionViews"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cdp",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICdpViews"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "collateral",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ICollateralViews"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "denomOf",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAllCollateralParams",
    "inputs": [],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "internalType": "struct FrontendLens.CollateralParams[]",
        "components": [
          {
            "name": "denom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "currentMaxLTV",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "tempLtv",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxThresholdToDelay",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "enabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "isInOnboarding",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "onboardingWindowEnd",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "supplyCapRegistered",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "supplyCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "currentSupply",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getCollateralParamsRange",
    "inputs": [
      {
        "name": "start",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "count",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "internalType": "struct FrontendLens.CollateralParams[]",
        "components": [
          {
            "name": "denom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "currentMaxLTV",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "tempLtv",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxThresholdToDelay",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "enabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "isInOnboarding",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "onboardingWindowEnd",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "supplyCapRegistered",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "supplyCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "currentSupply",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "liveFeeAuctions",
    "inputs": [],
    "outputs": [
      {
        "name": "out",
        "type": "tuple[]",
        "internalType": "struct FrontendLens.LiveAuction[]",
        "components": [
          {
            "name": "denom",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "amount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "startTime",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "tokenOf",
    "inputs": [
      {
        "name": "denom",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  }
] as const
