// AUTO-GENERATED by scripts/sync-abis.ts from membrane-solidity out/Governance.sol — do not edit.
export const governanceAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "governance_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "cfg",
        "type": "tuple",
        "internalType": "struct Governance.Config",
        "components": [
          {
            "name": "minimum_total_stake",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "vesting_voting_power_multiplier",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "proposal_voting_period",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expedited_proposal_voting_period",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "proposal_effective_delay",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "proposal_expiration_period",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "proposal_required_stake",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "proposal_required_quorum",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "proposal_required_threshold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "quadratic_voting",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "acceptOwnerTransfer",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cancelConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "cancelOwnerTransfer",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "castVote",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "vote",
        "type": "uint8",
        "internalType": "enum Governance.VoteOption"
      },
      {
        "name": "voting_power",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "config",
    "inputs": [],
    "outputs": [
      {
        "name": "minimum_total_stake",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "vesting_voting_power_multiplier",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "proposal_voting_period",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expedited_proposal_voting_period",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "proposal_effective_delay",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "proposal_expiration_period",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "proposal_required_stake",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "proposal_required_quorum",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "proposal_required_threshold",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "quadratic_voting",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "endProposal",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "total_voting_power",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "executeConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "executeProposal",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getActiveProposal",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Governance.Proposal",
        "components": [
          {
            "name": "proposal_id",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "submitter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum Governance.ProposalStatus"
          },
          {
            "name": "aligned_power",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "for_power",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "against_power",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amendment_power",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "removal_power",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "start_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "end_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "delayed_end_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiration_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expedited",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "expedited_extended",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "title",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "description",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "link",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "messages",
            "type": "tuple[]",
            "internalType": "struct Governance.ProposalMessage[]",
            "components": [
              {
                "name": "target",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "data",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMessageCount",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPendingProposal",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Governance.Proposal",
        "components": [
          {
            "name": "proposal_id",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "submitter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum Governance.ProposalStatus"
          },
          {
            "name": "aligned_power",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "for_power",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "against_power",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amendment_power",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "removal_power",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "start_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "end_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "delayed_end_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expiration_time",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "expedited",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "expedited_extended",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "title",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "description",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "link",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "messages",
            "type": "tuple[]",
            "internalType": "struct Governance.ProposalMessage[]",
            "components": [
              {
                "name": "target",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "data",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getProposalPowers",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "aligned",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "forP",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "against",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amendment",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "removal",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getProposalStatus",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum Governance.ProposalStatus"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getProposalTimes",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "startTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "endTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "delayedEnd",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expirationTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "governance",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasVoted",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "stakingContract_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isActive",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isInitialized",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isPending",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingChanges",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "proposer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "createdAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proposal_count",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proposeOwnerTransfer",
    "inputs": [
      {
        "name": "proposed",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "removeCompletedProposal",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requestConfigChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "stakingVotingPower",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IStakingVotingPower"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "submitProposal",
    "inputs": [
      {
        "name": "input",
        "type": "tuple",
        "internalType": "struct Governance.SubmitInput",
        "components": [
          {
            "name": "title",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "description",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "link",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "messages",
            "type": "tuple[]",
            "internalType": "struct Governance.ProposalMessage[]",
            "components": [
              {
                "name": "target",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "data",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "submitter_voting_power",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "total_system_stake",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expedited",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "pid",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "updateGovernance",
    "inputs": [
      {
        "name": "newGovernance",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "ConfigChangeCancelled",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigChangeExecuted",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConfigChangeRequested",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newValue",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      },
      {
        "name": "proposer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GovernanceUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "by",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnerTransferAccepted",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnerTransferProposed",
    "inputs": [
      {
        "name": "current",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "proposed",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipRenounced",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProposalEnded",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "status",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum Governance.ProposalStatus"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProposalExecuted",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProposalExtended",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "newEnd",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "newDelayedEnd",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "newExpiration",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProposalPromoted",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProposalRemoved",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProposalSubmitted",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "submitter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "expedited",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "status",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum Governance.ProposalStatus"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StakingContractUpdated",
    "inputs": [
      {
        "name": "previous",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "current",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VoteCast",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "voter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "option",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum Governance.VoteOption"
      },
      {
        "name": "weight",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlignOnlyForPending",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyVoted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CannotRemove",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ChangeAlreadyPending",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ConfigOutOfBounds",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExecutionFailed",
    "inputs": [
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ExpiredProposal",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientTotalStake",
    "inputs": [
      {
        "name": "supplied",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minimum",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoPendingChange",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotGovernance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitialized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwnerOrGovernance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPendingOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnerGovernanceCollision",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProposalNotActiveOrPending",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProposalNotFound",
    "inputs": [
      {
        "name": "proposalId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ProposalNotPassed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SubmitterCannotVote",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TimelockExpired",
    "inputs": [
      {
        "name": "nowTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "expireTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "TimelockNotElapsed",
    "inputs": [
      {
        "name": "nowTime",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "unlockTime",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "TooEarlyToExecute",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownConfigField",
    "inputs": [
      {
        "name": "fieldId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "VotingClosed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VotingNotEnded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroVotingPower",
    "inputs": []
  }
] as const
