/**
 * Sync contract ABIs from the membrane-solidity Foundry build into contracts/abis/.
 *
 * Usage: pnpm sync-abis   (set MEMBRANE_SOLIDITY_PATH to override the sibling-repo default)
 *
 * Emits one `export const <name>Abi = [...] as const` module per contract so viem/wagmi
 * infer full call types from the ABI (abitype). Re-run after any contract change.
 */
import * as fs from 'fs'
import * as path from 'path'

const SOLIDITY_ROOT = process.env.MEMBRANE_SOLIDITY_PATH ?? path.resolve(__dirname, '../../membrane-solidity')
const OUT_DIR = path.join(SOLIDITY_ROOT, 'out')
const DEST_DIR = path.resolve(__dirname, '../contracts/abis')

/** Solidity contract name -> emitted module/export base name */
const CONTRACTS: Record<string, string> = {
  Cdp: 'cdp',
  LtvDisco: 'ltvDisco',
  LiquidationEngine: 'liquidationEngine',
  LiqQueue: 'liqQueue',
  Transmuter: 'transmuter',
  Acquisition: 'acquisition',
  Staking: 'staking',
  Governance: 'governance',
  RevenueDistributor: 'revenueDistributor',
  Oracle: 'oracle',
  TwalOracle: 'twalOracle',
  PointsSystem: 'pointsSystem',
  SystemDiscounts: 'systemDiscounts',
  Auction: 'auction',
  Vesting: 'vesting',
}

function main() {
  if (!fs.existsSync(OUT_DIR)) {
    console.error(`Foundry out/ not found at ${OUT_DIR} — run \`forge build\` in membrane-solidity first,`)
    console.error('or set MEMBRANE_SOLIDITY_PATH.')
    process.exit(1)
  }
  fs.mkdirSync(DEST_DIR, { recursive: true })

  const written: string[] = []
  const missing: string[] = []

  for (const [solName, exportBase] of Object.entries(CONTRACTS)) {
    const artifact = path.join(OUT_DIR, `${solName}.sol`, `${solName}.json`)
    if (!fs.existsSync(artifact)) {
      missing.push(solName)
      continue
    }
    const { abi } = JSON.parse(fs.readFileSync(artifact, 'utf8'))
    const body =
      `// AUTO-GENERATED by scripts/sync-abis.ts from membrane-solidity out/${solName}.sol — do not edit.\n` +
      `export const ${exportBase}Abi = ${JSON.stringify(abi, null, 2)} as const\n`
    fs.writeFileSync(path.join(DEST_DIR, `${exportBase}.ts`), body)
    written.push(exportBase)
  }

  const index = written.map((n) => `export { ${n}Abi } from './${n}'`).join('\n') + '\n'
  fs.writeFileSync(path.join(DEST_DIR, 'index.ts'), index)

  console.log(`Wrote ${written.length} ABIs to contracts/abis/: ${written.join(', ')}`)
  if (missing.length) console.warn(`Missing artifacts (not built?): ${missing.join(', ')}`)
}

main()
