// THE DEFAULT WALLET IS REAL, AND IT IS STILL A STORY.
//
// Two failure modes this file exists to catch:
//
//  1. The committed snapshot rots or is edited by hand into something that no longer
//     parses as a position (public/data/demo-carry.json is generated by
//     scripts/snapshot-demo-carry.mjs and must never be hand-edited).
//
//  2. The demo quietly becomes a NON-EVENT. A landing page whose default wallet has
//     no cost to save AND survives the crash untouched has nothing to show. The last
//     test refuses that: the snapshot must either save real money on the deployed
//     slice, or get liquidated on the source protocol over the measured Oct 10 window.

import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { carryCost } from '@/lib/position-sim/carryCost'
import { MAX_LIQ_FEE, measuredRepayFraction, runComparison } from '@/lib/position-sim/compare'
import {
  DEMO_ADDRESS,
  DEMO_SNAPSHOT_DATE,
  DEMO_SNAPSHOT_NOTE,
  demoDetection,
  demoPosition,
  demoSummary,
} from '@/lib/position-sim/demo'
import { weightedMembraneLine } from '@/lib/position-sim/membrane'
import { buildPricePath, type Oct10Manifest, type Oct10Series } from '@/lib/position-sim/scenario'
import { toVenueRecall } from '@/lib/position-sim/venues'
import type { ProtocolPosition } from '@/lib/position-sim/types'

const DATA = join(process.cwd(), 'public', 'data')
const read = (p: string) => JSON.parse(readFileSync(join(DATA, p), 'utf8'))

const fixture = read('demo-carry.json')

/** Same default the page picks (Simulator.tsx defaultLiqFee) — matched to the source
 *  protocol's own bonus so nothing is handed to Membrane. */
function defaultLiqFee(p: ProtocolPosition): number {
  const priced = p.collateral.filter((c) => c.liquidationBonus !== null)
  const value = priced.reduce((a, c) => a + c.valueUsd, 0)
  if (value === 0) return MAX_LIQ_FEE
  return Math.min(
    MAX_LIQ_FEE,
    Math.max(
      0,
      priced.reduce((a, c) => a + (c.liquidationBonus as number) * c.valueUsd, 0) / value,
    ),
  )
}

/** The Oct 10 run, exactly as the page assembles it, but off disk. */
function oct10Run() {
  const series = read('oct10-2025/prices-1m.json') as Oct10Series
  const manifest = read('oct10-2025/manifest.json') as Oct10Manifest
  const protocols = read('oct10-2025/protocols.json')
  const position = demoPosition()
  const symbols = [
    ...position.collateral.map((c) => c.symbol),
    ...position.debt.map((d) => d.symbol),
  ]
  const { path, unpriced } = buildPricePath(series, manifest, symbols)
  const repay = measuredRepayFraction(position.protocol, protocols.measuredLiquidations)
  return runComparison(position, path, unpriced, {
    membraneMaxLtv: weightedMembraneLine(position.collateral).maxLtv,
    membraneLiqFee: defaultLiqFee(position),
    venue: toVenueRecall(demoDetection()),
    sourceRepayFraction: repay.fraction,
    sourceRepayFractionLabel: repay.label,
    scenarioLabel: 'oct10',
  })
}

describe('the committed demo snapshot', () => {
  it('parses, and carries the fields the page reads', () => {
    expect(fixture.provenance).toBe('onchain snapshot')
    expect(fixture.address).toMatch(/^0x[0-9a-fA-F]{40}$/)
    expect(fixture.block).toBeGreaterThan(0)
    expect(Number.isFinite(Date.parse(fixture.readAt))).toBe(true)
    expect(fixture.position).toBeTruthy()
    expect(fixture.detection).toBeTruthy()
  })

  it('is a real wallet, not the invented worked example', () => {
    expect(DEMO_ADDRESS).toBe(fixture.address)
    expect(DEMO_ADDRESS).not.toBe('0x0000000000000000000000000000000000000000')
    expect(demoPosition().provenance.kind).toBe('onchain')
    expect(DEMO_SNAPSHOT_NOTE).toContain(DEMO_SNAPSHOT_DATE)
  })

  it('holds real debt', () => {
    const p = demoPosition()
    expect(p.totalDebtUsd).toBeGreaterThan(0)
    expect(p.totalCollateralUsd).toBeGreaterThan(p.totalDebtUsd)
    expect(p.debt.length).toBeGreaterThan(0)
  })

  it('summarises in 25 words or fewer', () => {
    expect(demoSummary().split(/\s+/).length).toBeLessThanOrEqual(25)
  })

  it('prices the fixed interest on the deployed slice whenever the snapshot has a rate', () => {
    const c = carryCost(demoPosition(), demoDetection())
    const hasApr = demoPosition().debt.some((d) => d.borrowApr !== null)
    if (hasApr && c.deployedUsd > 0) {
      expect(c.fixedCostOnCoveredUsd).toBeGreaterThan(0)
      // The covered slice is never the whole bill unless the whole priced debt is covered.
      expect(c.fixedCostOnCoveredUsd).toBeLessThanOrEqual(c.annualCostUsd + 1e-9)
      expect(c.coveredDebtUsd).toBeLessThanOrEqual(c.pricedDebtUsd + 1e-9)
    } else {
      expect(c.fixedCostOnCoveredUsd).toBe(0)
    }
  })

  it('is never a non-event: it either has a carry cost line or it gets liquidated', () => {
    const savings = carryCost(demoPosition(), demoDetection()).fixedCostOnCoveredUsd
    if (savings > 0) {
      expect(savings).toBeGreaterThan(0)
      return
    }
    const cmp = oct10Run()
    const liquidated = cmp.source.events.some((e) => e.kind === 'liquidation')
    expect(liquidated).toBe(true)
  })
})
