import { createPublicClient, http, parseAbi, type Hex, type PublicClient } from 'viem'
import { anvil } from 'viem/chains'

import addresses from '@/config/evm/addresses.json'

export const DISCO_CHAIN_ID = 31337
export const DEPOSIT_KEY_RE = /^0x[0-9a-fA-F]{64}$/

// These are the public struct getters in LtvDisco.sol, in declaration order.
// Do not substitute Collateral.pendingLtvMove: it is an asset glide, not a deposit intent.
export const discoDecisionAbi = parseAbi([
  'function config() view returns (uint256 minimumDeposit, uint256 unstakingPeriod, uint256 unstakeExecutionWindow, uint256 ltvSwitchingPeriod, uint256 ltvSwitchingExecutionWindow, uint256 managerFeeChangePeriod, uint256 managerFeeChangeExecutionWindow, uint256 affiliateFee, uint256 maxManagementFee)',
  'function backingDeposits(bytes32) view returns (address user, address manager, address depositor, address revenueDestination, uint256 vaultTokens, uint256 lastClaimedAt, uint256 startTime, bool exists)',
  'function depositLTVIntent(bytes32) view returns (uint256)',
  'function lowerLTVIntents(uint256) view returns (uint256 id, bytes32 depositKey, bytes32 asset, address user, uint256 srcSlot, uint256 dstSlot, uint256 vtAmount, uint256 createdAt, uint256 unlockTime, uint256 expireTime, bool active)',
])

const configuredAddress = (addresses as Record<string, { ltvDisco?: string }>)[
  String(DISCO_CHAIN_ID)
]?.ltvDisco
if (!configuredAddress || !/^0x[0-9a-fA-F]{40}$/.test(configuredAddress)) {
  throw new Error('Missing configured local LtvDisco address')
}
export const LOCAL_DISCO_ADDRESS = configuredAddress as `0x${string}`

export type DiscoDecisionSnapshot = {
  chainId: 31337
  depositKey: Hex
  discoAddress: `0x${string}`
  blockNumber: string
  blockHash: Hex
  blockTimestamp: string
  depositOwner: `0x${string}`
  ltvSwitchingPeriodSeconds: string
  executionWindowSeconds: string
  intent: null | {
    id: string
    createdAt: string
    unlockTime: string
    expireTime: string
    srcSlot: string
    dstSlot: string
    asset: Hex
    vtAmount: string
    phase: 'waiting' | 'executable' | 'expired'
  }
}

export class DiscoSnapshotError extends Error {
  constructor(
    public readonly reason:
      | 'wrong_chain'
      | 'not_deployed'
      | 'deposit_missing'
      | 'inconsistent_state'
      | 'block_drift',
  ) {
    super(reason)
  }
}

export function localDiscoClient(): PublicClient {
  // The address book has only an Anvil deployment. No chain-1 fallback is allowed.
  const url = process.env.NEXT_PUBLIC_LOCAL_RPC_URL || 'http://127.0.0.1:8545'
  return createPublicClient({
    chain: anvil,
    transport: http(url, { timeout: 6_000, retryCount: 0 }),
  }) as PublicClient
}

export async function readDiscoDecisionSnapshot(
  client: PublicClient,
  depositKey: Hex,
  address: `0x${string}` = LOCAL_DISCO_ADDRESS,
): Promise<DiscoDecisionSnapshot> {
  if (!DEPOSIT_KEY_RE.test(depositKey)) throw new DiscoSnapshotError('deposit_missing')
  if ((await client.getChainId()) !== DISCO_CHAIN_ID) throw new DiscoSnapshotError('wrong_chain')

  const block = await client.getBlock({ blockTag: 'finalized' })
  if (block.number === null || !block.hash) throw new DiscoSnapshotError('block_drift')
  const blockNumber = block.number
  const code = await client.getCode({ address, blockNumber })
  if (!code || code === '0x') throw new DiscoSnapshotError('not_deployed')

  // Sequence is deliberately bounded and block-pinned. Viem decodes the exact
  // autogenerated Solidity getter tuples, not inferred fields or deploy defaults.
  const config = await client.readContract({
    address,
    abi: discoDecisionAbi,
    functionName: 'config',
    blockNumber,
  })
  const deposit = await client.readContract({
    address,
    abi: discoDecisionAbi,
    functionName: 'backingDeposits',
    args: [depositKey],
    blockNumber,
  })
  if (!deposit[7]) throw new DiscoSnapshotError('deposit_missing')
  const intentId = await client.readContract({
    address,
    abi: discoDecisionAbi,
    functionName: 'depositLTVIntent',
    args: [depositKey],
    blockNumber,
  })
  let intent: DiscoDecisionSnapshot['intent'] = null
  if (intentId !== 0n) {
    const row = await client.readContract({
      address,
      abi: discoDecisionAbi,
      functionName: 'lowerLTVIntents',
      args: [intentId],
      blockNumber,
    })
    if (
      row[0] !== intentId ||
      row[1].toLowerCase() !== depositKey.toLowerCase() ||
      row[3].toLowerCase() !== deposit[0].toLowerCase() ||
      !row[10] ||
      row[8] < row[7] ||
      row[9] < row[8]
    ) {
      throw new DiscoSnapshotError('inconsistent_state')
    }
    intent = {
      id: intentId.toString(),
      createdAt: row[7].toString(),
      unlockTime: row[8].toString(),
      expireTime: row[9].toString(),
      srcSlot: row[4].toString(),
      dstSlot: row[5].toString(),
      asset: row[2],
      vtAmount: row[6].toString(),
      phase:
        block.timestamp < row[8] ? 'waiting' : block.timestamp <= row[9] ? 'executable' : 'expired',
    }
  }

  // The finalized head may advance during these reads. Re-read the pinned
  // canonical block, not the moving finalized tag, to detect an actual reorg.
  const check = await client.getBlock({ blockNumber })
  if (check.number !== blockNumber || check.hash?.toLowerCase() !== block.hash.toLowerCase()) {
    throw new DiscoSnapshotError('block_drift')
  }
  return {
    chainId: DISCO_CHAIN_ID,
    depositKey,
    discoAddress: address,
    blockNumber: blockNumber.toString(),
    blockHash: block.hash,
    blockTimestamp: block.timestamp.toString(),
    depositOwner: deposit[0],
    ltvSwitchingPeriodSeconds: config[3].toString(),
    executionWindowSeconds: config[4].toString(),
    intent,
  }
}
