import {sameHolderExitAssessment} from '/Users/EBmic/membrane-app/pages/api/carry/holder-exit-assessment'
import {agreeHolderExitCapacityQuotes} from '/Users/EBmic/membrane-app/lib/carry/holderExitCapacity'
import {it} from 'vitest'
import {createPublicClient,http} from 'viem'
import {mainnet} from 'viem/chains'
import {readHolderExitAssessment,isCurrentHolderExitAssessment} from '/Users/EBmic/membrane-app/lib/carry/holderExitAssessment'
import {configuredProviders,readProviderPolicy} from '/Users/EBmic/membrane-app/scripts/research/carry-depth-quote-archive.mjs'
import {readFileSync,openSync,writeSync,fsyncSync,closeSync,constants} from 'node:fs'
import {createHash} from 'node:crypto'
it('diagnose exact production reader errors without API blanket catch',async()=>{
 const input=JSON.parse(readFileSync('/private/tmp/eurcv-additional-holder-default-live-2026-10-10T04-17-31.129Z-71108c8a-ec8d-4cab-8fbb-50f6e8d7ca51/request.json','utf8')).input
 const providers=configuredProviders(null,readProviderPolicy()),rows=[],assessments:any[]=[]
 if(providers.length!==2||providers[0].host!=='eth-mainnet.g.alchemy.com'||providers[1].host!=='rpc.ankr.com')throw Error('provider_pair_invalid')
 const safe=(e:any)=>{const rows=[];for(let i=0;e&&i<6;i++,e=e.cause){const reason=typeof e.message==='string'&&/^(holder_exit|morpho_exit|morpho_quote)_[a-z0-9_]{1,80}$/.test(e.message)?e.message:null;const names=['RpcRequestError','HttpRequestError','ContractFunctionExecutionError','ContractFunctionRevertedError','CallExecutionError','TimeoutError','Error','TypeError'];const codes=['ENOTFOUND','EAI_AGAIN','ECONNREFUSED','ECONNRESET','ETIMEDOUT','UND_ERR_CONNECT_TIMEOUT','UNABLE_TO_VERIFY_LEAF_SIGNATURE','CERT_HAS_EXPIRED','UNABLE_TO_GET_ISSUER_CERT_LOCALLY'];rows.push({name:names.includes(e.name)?e.name:'other_error',reason,code:Number.isSafeInteger(e.code)?e.code:codes.includes(e.code)?e.code:null,status:Number.isInteger(e.status)&&e.status>=100&&e.status<=599?e.status:null})}return rows}
 for(const p of providers){const client=createPublicClient({chain:mainnet,transport:http(p.url,{timeout:8000,retryCount:0})});const clients={direct:client,apy:client,tracked:client,morpho:client};const started=Date.now();try{const result=await readHolderExitAssessment(clients as never,input,{includeCapacityFacts:true,includeStusdsProtocolCapacity:true});assessments.push({host:p.host,assessment:result});rows.push({host:p.host,phase:'production_holder_reader',ok:true,status:result.status,source:result.source,elapsedMs:Date.now()-started})}catch(e){rows.push({host:p.host,phase:'production_holder_reader',ok:false,errorChain:safe(e),elapsedMs:Date.now()-started})}}
 const checkedAtMs=Date.now(); const fresh=assessments.map(x=>({host:x.host,current:isCurrentHolderExitAssessment(x.assessment,checkedAtMs),sourceAgeMs:checkedAtMs-Date.parse(x.assessment.source.blockTime)}));let same:any=null,capacityAgreement:any=null,differingPaths:string[]=[];if(assessments.length===2){const a=assessments[0],b=assessments[1];same=sameHolderExitAssessment(a.assessment,b.assessment);capacityAgreement=Boolean(agreeHolderExitCapacityQuotes({host:a.host,quote:a.assessment.capacityQuote},{host:b.host,quote:b.assessment.capacityQuote},checkedAtMs));const normalize=(a:any)=>JSON.parse(JSON.stringify({...a,capacityQuote:undefined,susdeHolderFacts:undefined,susdeProtocolCapacityObservation:undefined,stusdsProtocolCapacityObservation:undefined,morphoV2ProtocolCapacityObservation:undefined,morphoHolderPositionObservation:undefined,cometFacts:undefined,cometFactsAgreement:undefined,source:{...a.source,originValidation:'two_provider'},pyusdYieldQueueCondition:undefined}));const diff=(a:any,b:any,p:string)=>{if(JSON.stringify(a)===JSON.stringify(b))return;if(a&&b&&typeof a==='object'&&typeof b==='object'){for(const k of new Set([...Object.keys(a),...Object.keys(b)]))diff(a[k],b[k],p+'/'+k)}else if(differingPaths.length<32)differingPaths.push(p)};diff(normalize(a.assessment),normalize(b.assessment),'');}for(let i=0;i<assessments.length;i++){const raw=Buffer.from(JSON.stringify(assessments[i].assessment));if(raw.length>2*1024*1024)throw Error('diagnostic_assessment_bound');const path='/private/tmp/eurcv-holder-corrob-gate-diagnostic-oct10-53080a40-68fb-45d9-9e21-a0806a5f808b/assessment-'+i+'.json';const f=openSync(path,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);try{let off=0;while(off<raw.length)off+=writeSync(f,raw,off,raw.length-off);fsyncSync(f)}finally{closeSync(f)}if(!readFileSync(path).equals(raw))throw Error('diagnostic_assessment_readback');} const result={checkedAtMs,fresh,same,capacityAgreement,differingPaths,schema:'eurcv_production_corrob_gate_diagnostic_v1',researchOnly:true,executionQualified:false,forecastEligibility:false,SDKPhysicalStarts:null,rows};const bytes=Buffer.from(JSON.stringify(result)+'\n');if(bytes.length>8192)throw Error('diagnostic_metadata_bound');const target=new URL('file:///private/tmp/eurcv-holder-corrob-gate-diagnostic-oct10-53080a40-68fb-45d9-9e21-a0806a5f808b/gate-result.json');const fd=openSync(target,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);try{let offset=0;while(offset<bytes.length)offset+=writeSync(fd,bytes,offset,bytes.length-offset);fsyncSync(fd)}finally{closeSync(fd)}if(!readFileSync(target).equals(bytes))throw Error('diagnostic_readback');console.log(JSON.stringify({...result,resultFile:target.pathname,bytes:bytes.length,fileSha256:createHash('sha256').update(bytes).digest('hex')}))
},40000)
